### ISSUE TITLE
Better logging when file is not found for route

### ISSUE THREAD

**Issue by pheyvaer** [KNowledgeOnWebScale/walder#48]

**Comment by mvanbrab** [comment]
Please explain how to evoke the problem.

I tried by changing config.yaml line 41 (added the underscores, to specify a file that does not exist):
`x-walder-input-text/html: songs__________.handlebars`
Is that it?

The above results in an error at runtime from fs.readFile() in html-converter.js
and finally in a console.error() call in content-negotiation-handler.js:
`Content negotiation (reformatting) error: Reading the file "/home/mavbraba/git-workingcopies/project-walder/walder/example/views/songs__________.handlebars" failed.`

What is the suggestied solution?
- replace the console.error() call by a logger.error() call
- detect and log the error condition at activation time rather than at run time
(I'd suggest both)

**Comment by pheyvaer** [comment]
Indeed that is the error with `fs.readFile()` that this issue is about. 

- The runtime error should be hidden.
- Only the nicely printed error should remain.
- Optional: detect and log the error condition at activation time

So I agree with your suggestions 😄

**Comment by mvanbrab** [comment]
I included the optional suggestion (which resulted in extending/modifying the tests as well).
